// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Philcosa.Infrastructure.Persistence.Contexts;

namespace Philcosa.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 63)
                .HasAnnotation("ProductVersion", "5.0.5")
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

            modelBuilder.Entity("Philcosa.Domain.Entities.Country", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<string>("Code")
                        .HasColumnType("text");

                    b.Property<DateTime>("Created")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text");

                    b.Property<DateTime?>("LastModified")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("LastModifiedBy")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Countries");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Code = "VEN",
                            Created = new DateTime(2021, 5, 19, 14, 18, 39, 109, DateTimeKind.Local).AddTicks(4233),
                            CreatedBy = "DataSeed",
                            Name = "Venda"
                        },
                        new
                        {
                            Id = 2,
                            Code = "TRA",
                            Created = new DateTime(2021, 5, 19, 14, 18, 39, 114, DateTimeKind.Local).AddTicks(5369),
                            CreatedBy = "DataSeed",
                            Name = "Transkei"
                        },
                        new
                        {
                            Id = 3,
                            Code = "CIS",
                            Created = new DateTime(2021, 5, 19, 14, 18, 39, 114, DateTimeKind.Local).AddTicks(5476),
                            CreatedBy = "DataSeed",
                            Name = "Ciskei"
                        },
                        new
                        {
                            Id = 4,
                            Code = "BOP",
                            Created = new DateTime(2021, 5, 19, 14, 18, 39, 114, DateTimeKind.Local).AddTicks(5480),
                            CreatedBy = "DataSeed",
                            Name = "Bophuthatswana"
                        },
                        new
                        {
                            Id = 5,
                            Code = "SWA",
                            Created = new DateTime(2021, 5, 19, 14, 18, 39, 114, DateTimeKind.Local).AddTicks(5483),
                            CreatedBy = "DataSeed",
                            Name = "South West Africa"
                        },
                        new
                        {
                            Id = 6,
                            Code = "RSA",
                            Created = new DateTime(2021, 5, 19, 14, 18, 39, 114, DateTimeKind.Local).AddTicks(5487),
                            CreatedBy = "DataSeed",
                            Name = "South Africa"
                        },
                        new
                        {
                            Id = 7,
                            Code = "NAM",
                            Created = new DateTime(2021, 5, 19, 14, 18, 39, 114, DateTimeKind.Local).AddTicks(5490),
                            CreatedBy = "DataSeed",
                            Name = "Namibia"
                        });
                });

            modelBuilder.Entity("Philcosa.Domain.Entities.IssuedByEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<string>("Code")
                        .HasColumnType("text");

                    b.Property<DateTime>("Created")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text");

                    b.Property<DateTime?>("LastModified")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("LastModifiedBy")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("IssuedByEntities");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Created = new DateTime(2021, 5, 19, 14, 18, 39, 127, DateTimeKind.Local).AddTicks(8291),
                            CreatedBy = "DataSeed",
                            Name = "Kempton Park Philatelic Society (Kemp kard)"
                        },
                        new
                        {
                            Id = 2,
                            Created = new DateTime(2021, 5, 19, 14, 18, 39, 127, DateTimeKind.Local).AddTicks(8984),
                            CreatedBy = "DataSeed",
                            Name = "First Day Fabrics (Silk)"
                        },
                        new
                        {
                            Id = 3,
                            Created = new DateTime(2021, 5, 19, 14, 18, 39, 127, DateTimeKind.Local).AddTicks(9001),
                            CreatedBy = "DataSeed",
                            Name = "South African Air Force (Aerobic)"
                        },
                        new
                        {
                            Id = 4,
                            Created = new DateTime(2021, 5, 19, 14, 18, 39, 127, DateTimeKind.Local).AddTicks(9003),
                            CreatedBy = "DataSeed",
                            Name = "SA Army"
                        },
                        new
                        {
                            Id = 5,
                            Created = new DateTime(2021, 5, 19, 14, 18, 39, 127, DateTimeKind.Local).AddTicks(9005),
                            CreatedBy = "DataSeed",
                            Name = "Namib AirAir Namibia (Delivery flights)"
                        },
                        new
                        {
                            Id = 6,
                            Created = new DateTime(2021, 5, 19, 14, 18, 39, 127, DateTimeKind.Local).AddTicks(9008),
                            CreatedBy = "DataSeed",
                            Name = "United Nations"
                        },
                        new
                        {
                            Id = 7,
                            Created = new DateTime(2021, 5, 19, 14, 18, 39, 127, DateTimeKind.Local).AddTicks(9010),
                            CreatedBy = "DataSeed",
                            Name = "World Wildlife Fund"
                        },
                        new
                        {
                            Id = 8,
                            Created = new DateTime(2021, 5, 19, 14, 18, 39, 127, DateTimeKind.Local).AddTicks(9012),
                            CreatedBy = "DataSeed",
                            Name = "Namib AirAir Namibia"
                        },
                        new
                        {
                            Id = 9,
                            Created = new DateTime(2021, 5, 19, 14, 18, 39, 127, DateTimeKind.Local).AddTicks(9013),
                            CreatedBy = "DataSeed",
                            Name = "First Day Fabrics (Gold)"
                        },
                        new
                        {
                            Id = 10,
                            Created = new DateTime(2021, 5, 19, 14, 18, 39, 127, DateTimeKind.Local).AddTicks(9016),
                            CreatedBy = "DataSeed",
                            Name = "Kempton Park Philatelic Society (Kemp Air)"
                        },
                        new
                        {
                            Id = 11,
                            Created = new DateTime(2021, 5, 19, 14, 18, 39, 127, DateTimeKind.Local).AddTicks(9017),
                            CreatedBy = "DataSeed",
                            Name = "The Railway Society"
                        },
                        new
                        {
                            Id = 12,
                            Created = new DateTime(2021, 5, 19, 14, 18, 39, 127, DateTimeKind.Local).AddTicks(9019),
                            CreatedBy = "DataSeed",
                            Name = "SA Police"
                        },
                        new
                        {
                            Id = 13,
                            Created = new DateTime(2021, 5, 19, 14, 18, 39, 127, DateTimeKind.Local).AddTicks(9020),
                            CreatedBy = "DataSeed",
                            Name = "Simonstown Navy Museum"
                        },
                        new
                        {
                            Id = 14,
                            Created = new DateTime(2021, 5, 19, 14, 18, 39, 127, DateTimeKind.Local).AddTicks(9022),
                            CreatedBy = "DataSeed",
                            Name = "Nam Post"
                        },
                        new
                        {
                            Id = 15,
                            Created = new DateTime(2021, 5, 19, 14, 18, 39, 127, DateTimeKind.Local).AddTicks(9024),
                            CreatedBy = "DataSeed",
                            Name = "SA Defence Force"
                        },
                        new
                        {
                            Id = 16,
                            Created = new DateTime(2021, 5, 19, 14, 18, 39, 127, DateTimeKind.Local).AddTicks(9025),
                            CreatedBy = "DataSeed",
                            Name = "SA Post Office"
                        },
                        new
                        {
                            Id = 17,
                            Created = new DateTime(2021, 5, 19, 14, 18, 39, 127, DateTimeKind.Local).AddTicks(9027),
                            CreatedBy = "DataSeed",
                            Name = "Ship Society of SA"
                        },
                        new
                        {
                            Id = 18,
                            Created = new DateTime(2021, 5, 19, 14, 18, 39, 127, DateTimeKind.Local).AddTicks(9061),
                            CreatedBy = "DataSeed",
                            Name = "South African Airways"
                        },
                        new
                        {
                            Id = 19,
                            Created = new DateTime(2021, 5, 19, 14, 18, 39, 127, DateTimeKind.Local).AddTicks(9062),
                            CreatedBy = "DataSeed",
                            Name = "SA Philatelic Foundation"
                        },
                        new
                        {
                            Id = 20,
                            Created = new DateTime(2021, 5, 19, 14, 18, 39, 127, DateTimeKind.Local).AddTicks(9064),
                            CreatedBy = "DataSeed",
                            Name = "Federation"
                        },
                        new
                        {
                            Id = 21,
                            Created = new DateTime(2021, 5, 19, 14, 18, 39, 127, DateTimeKind.Local).AddTicks(9066),
                            CreatedBy = "DataSeed",
                            Name = "South African Airways Museum"
                        },
                        new
                        {
                            Id = 22,
                            Created = new DateTime(2021, 5, 19, 14, 18, 39, 127, DateTimeKind.Local).AddTicks(9067),
                            CreatedBy = "DataSeed",
                            Name = "Private"
                        },
                        new
                        {
                            Id = 23,
                            Created = new DateTime(2021, 5, 19, 14, 18, 39, 127, DateTimeKind.Local).AddTicks(9069),
                            CreatedBy = "DataSeed",
                            Name = "SA Transport Services"
                        },
                        new
                        {
                            Id = 24,
                            Created = new DateTime(2021, 5, 19, 14, 18, 39, 127, DateTimeKind.Local).AddTicks(9070),
                            CreatedBy = "DataSeed",
                            Name = "Simonstown Historical Society"
                        },
                        new
                        {
                            Id = 25,
                            Created = new DateTime(2021, 5, 19, 14, 18, 39, 127, DateTimeKind.Local).AddTicks(9072),
                            CreatedBy = "DataSeed",
                            Name = "Warner Pharmaceuticals"
                        },
                        new
                        {
                            Id = 26,
                            Created = new DateTime(2021, 5, 19, 14, 18, 39, 127, DateTimeKind.Local).AddTicks(9073),
                            CreatedBy = "DataSeed",
                            Name = "SA Air Force Museum (Original Series)"
                        },
                        new
                        {
                            Id = 27,
                            Created = new DateTime(2021, 5, 19, 14, 18, 39, 127, DateTimeKind.Local).AddTicks(9075),
                            CreatedBy = "DataSeed",
                            Name = "Kempton Park Philatelic Society (Kemp Maksikard)"
                        },
                        new
                        {
                            Id = 28,
                            Created = new DateTime(2021, 5, 19, 14, 18, 39, 127, DateTimeKind.Local).AddTicks(9077),
                            CreatedBy = "DataSeed",
                            Name = "SA Railway Services"
                        },
                        new
                        {
                            Id = 29,
                            Created = new DateTime(2021, 5, 19, 14, 18, 39, 127, DateTimeKind.Local).AddTicks(9078),
                            CreatedBy = "DataSeed",
                            Name = "Kempton Park Philatelic Society (Kemp Kover)"
                        },
                        new
                        {
                            Id = 30,
                            Created = new DateTime(2021, 5, 19, 14, 18, 39, 127, DateTimeKind.Local).AddTicks(9080),
                            CreatedBy = "DataSeed",
                            Name = "SA Air Force Museum (World War Series)"
                        },
                        new
                        {
                            Id = 31,
                            Created = new DateTime(2021, 5, 19, 14, 18, 39, 127, DateTimeKind.Local).AddTicks(9081),
                            CreatedBy = "DataSeed",
                            Name = "SA Air Force Museum (Spesials)"
                        },
                        new
                        {
                            Id = 32,
                            Created = new DateTime(2021, 5, 19, 14, 18, 39, 127, DateTimeKind.Local).AddTicks(9083),
                            CreatedBy = "DataSeed",
                            Name = "Foreign Airline"
                        },
                        new
                        {
                            Id = 33,
                            Created = new DateTime(2021, 5, 19, 14, 18, 39, 127, DateTimeKind.Local).AddTicks(9084),
                            CreatedBy = "DataSeed",
                            Name = "SA Navy"
                        },
                        new
                        {
                            Id = 34,
                            Created = new DateTime(2021, 5, 19, 14, 18, 39, 127, DateTimeKind.Local).AddTicks(9088),
                            CreatedBy = "DataSeed",
                            Name = "Caprivi Airways"
                        },
                        new
                        {
                            Id = 35,
                            Created = new DateTime(2021, 5, 19, 14, 18, 39, 127, DateTimeKind.Local).AddTicks(9090),
                            CreatedBy = "DataSeed",
                            Name = "SA Air Force Museum (Anniversary Flights)"
                        },
                        new
                        {
                            Id = 36,
                            Created = new DateTime(2021, 5, 19, 14, 18, 39, 127, DateTimeKind.Local).AddTicks(9091),
                            CreatedBy = "DataSeed",
                            Name = "Flitestar"
                        },
                        new
                        {
                            Id = 37,
                            Created = new DateTime(2021, 5, 19, 14, 18, 39, 127, DateTimeKind.Local).AddTicks(9093),
                            CreatedBy = "DataSeed",
                            Name = "Airphilsa"
                        });
                });

            modelBuilder.Entity("Philcosa.Domain.Entities.Postcard", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<string>("Alberta")
                        .HasColumnType("text");

                    b.Property<string>("AmountIssued")
                        .HasColumnType("text");

                    b.Property<string>("Atlas")
                        .HasColumnType("text");

                    b.Property<int?>("CountryId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("Created")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("IdOnDate")
                        .HasColumnType("text");

                    b.Property<int?>("IssuedById")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("LastModified")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("LastModifiedBy")
                        .HasColumnType("text");

                    b.Property<string>("Number")
                        .HasColumnType("text");

                    b.Property<string>("Path")
                        .HasColumnType("text");

                    b.Property<DateTime>("PostcardDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int?>("PostcardTypeId")
                        .HasColumnType("integer");

                    b.Property<int?>("PostcardValueId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("CountryId")
                        .IsUnique();

                    b.HasIndex("IssuedById")
                        .IsUnique();

                    b.HasIndex("PostcardTypeId")
                        .IsUnique();

                    b.HasIndex("PostcardValueId")
                        .IsUnique();

                    b.ToTable("Postcards");
                });

            modelBuilder.Entity("Philcosa.Domain.Entities.PostcardTheme", b =>
                {
                    b.Property<int>("PostcardId")
                        .HasColumnType("integer");

                    b.Property<int>("ThemeId")
                        .HasColumnType("integer");

                    b.HasKey("PostcardId", "ThemeId");

                    b.HasIndex("ThemeId");

                    b.ToTable("PostcardThemes");
                });

            modelBuilder.Entity("Philcosa.Domain.Entities.PostcardType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<string>("Code")
                        .HasColumnType("text");

                    b.Property<DateTime>("Created")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text");

                    b.Property<DateTime?>("LastModified")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("LastModifiedBy")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("PostcardTypes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Code = "FDC",
                            Created = new DateTime(2021, 5, 19, 14, 18, 39, 118, DateTimeKind.Local).AddTicks(176),
                            CreatedBy = "DataSeed",
                            Name = "First Day"
                        },
                        new
                        {
                            Id = 2,
                            Code = "CMC",
                            Created = new DateTime(2021, 5, 19, 14, 18, 39, 118, DateTimeKind.Local).AddTicks(613),
                            CreatedBy = "DataSeed",
                            Name = "Comemorative"
                        },
                        new
                        {
                            Id = 3,
                            Code = "FLT",
                            Created = new DateTime(2021, 5, 19, 14, 18, 39, 118, DateTimeKind.Local).AddTicks(631),
                            CreatedBy = "DataSeed",
                            Name = "Flight"
                        },
                        new
                        {
                            Id = 4,
                            Code = "SLK",
                            Created = new DateTime(2021, 5, 19, 14, 18, 39, 118, DateTimeKind.Local).AddTicks(633),
                            CreatedBy = "DataSeed",
                            Name = "Silk"
                        },
                        new
                        {
                            Id = 5,
                            Code = "GLD",
                            Created = new DateTime(2021, 5, 19, 14, 18, 39, 118, DateTimeKind.Local).AddTicks(635),
                            CreatedBy = "DataSeed",
                            Name = "Gold Foiled"
                        },
                        new
                        {
                            Id = 6,
                            Code = "MIL",
                            Created = new DateTime(2021, 5, 19, 14, 18, 39, 118, DateTimeKind.Local).AddTicks(637),
                            CreatedBy = "DataSeed",
                            Name = "Military"
                        },
                        new
                        {
                            Id = 7,
                            Code = "FIL",
                            Created = new DateTime(2021, 5, 19, 14, 18, 39, 118, DateTimeKind.Local).AddTicks(639),
                            CreatedBy = "DataSeed",
                            Name = "Filatelic"
                        },
                        new
                        {
                            Id = 8,
                            Code = "BAL",
                            Created = new DateTime(2021, 5, 19, 14, 18, 39, 118, DateTimeKind.Local).AddTicks(641),
                            CreatedBy = "DataSeed",
                            Name = "Balloon"
                        },
                        new
                        {
                            Id = 9,
                            Code = "RWY",
                            Created = new DateTime(2021, 5, 19, 14, 18, 39, 118, DateTimeKind.Local).AddTicks(642),
                            CreatedBy = "DataSeed",
                            Name = "Railway"
                        });
                });

            modelBuilder.Entity("Philcosa.Domain.Entities.PostcardValue", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<string>("Code")
                        .HasColumnType("text");

                    b.Property<DateTime>("Created")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text");

                    b.Property<DateTime?>("LastModified")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("LastModifiedBy")
                        .HasColumnType("text");

                    b.Property<decimal?>("MaxValue")
                        .HasColumnType("numeric(18,6)");

                    b.Property<decimal?>("MinValue")
                        .HasColumnType("numeric(18,6)");

                    b.HasKey("Id");

                    b.ToTable("PostcardValues");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Code = "$",
                            Created = new DateTime(2021, 5, 19, 14, 18, 39, 119, DateTimeKind.Local).AddTicks(316),
                            CreatedBy = "DataSeed",
                            MaxValue = 5m,
                            MinValue = 0m
                        },
                        new
                        {
                            Id = 2,
                            Code = "$$",
                            Created = new DateTime(2021, 5, 19, 14, 18, 39, 119, DateTimeKind.Local).AddTicks(1243),
                            CreatedBy = "DataSeed",
                            MaxValue = 15m,
                            MinValue = 5.01m
                        },
                        new
                        {
                            Id = 3,
                            Code = "$$$",
                            Created = new DateTime(2021, 5, 19, 14, 18, 39, 119, DateTimeKind.Local).AddTicks(1305),
                            CreatedBy = "DataSeed",
                            MaxValue = 50m,
                            MinValue = 15.01m
                        },
                        new
                        {
                            Id = 4,
                            Code = "$$$$",
                            Created = new DateTime(2021, 5, 19, 14, 18, 39, 119, DateTimeKind.Local).AddTicks(1308),
                            CreatedBy = "DataSeed",
                            MaxValue = 150m,
                            MinValue = 50.01m
                        },
                        new
                        {
                            Id = 5,
                            Code = "$$$$$",
                            Created = new DateTime(2021, 5, 19, 14, 18, 39, 119, DateTimeKind.Local).AddTicks(1310),
                            CreatedBy = "DataSeed",
                            MaxValue = 500m,
                            MinValue = 150.01m
                        },
                        new
                        {
                            Id = 6,
                            Code = "$$$$$$",
                            Created = new DateTime(2021, 5, 19, 14, 18, 39, 119, DateTimeKind.Local).AddTicks(1312),
                            CreatedBy = "DataSeed",
                            MinValue = 500.01m
                        });
                });

            modelBuilder.Entity("Philcosa.Domain.Entities.Theme", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<DateTime>("Created")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text");

                    b.Property<DateTime?>("LastModified")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("LastModifiedBy")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Themes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Created = new DateTime(2021, 5, 19, 14, 18, 39, 124, DateTimeKind.Local).AddTicks(1628),
                            CreatedBy = "DataSeed",
                            Name = "ITU"
                        },
                        new
                        {
                            Id = 2,
                            Created = new DateTime(2021, 5, 19, 14, 18, 39, 124, DateTimeKind.Local).AddTicks(2089),
                            CreatedBy = "DataSeed",
                            Name = "Famous Persons"
                        },
                        new
                        {
                            Id = 3,
                            Created = new DateTime(2021, 5, 19, 14, 18, 39, 124, DateTimeKind.Local).AddTicks(2100),
                            CreatedBy = "DataSeed",
                            Name = "Sport"
                        },
                        new
                        {
                            Id = 4,
                            Created = new DateTime(2021, 5, 19, 14, 18, 39, 124, DateTimeKind.Local).AddTicks(2102),
                            CreatedBy = "DataSeed",
                            Name = "Police"
                        },
                        new
                        {
                            Id = 5,
                            Created = new DateTime(2021, 5, 19, 14, 18, 39, 124, DateTimeKind.Local).AddTicks(2105),
                            CreatedBy = "DataSeed",
                            Name = "UPU"
                        },
                        new
                        {
                            Id = 6,
                            Created = new DateTime(2021, 5, 19, 14, 18, 39, 124, DateTimeKind.Local).AddTicks(2110),
                            CreatedBy = "DataSeed",
                            Name = "Mandela"
                        },
                        new
                        {
                            Id = 7,
                            Created = new DateTime(2021, 5, 19, 14, 18, 39, 124, DateTimeKind.Local).AddTicks(2112),
                            CreatedBy = "DataSeed",
                            Name = "Fishing/Angling"
                        },
                        new
                        {
                            Id = 8,
                            Created = new DateTime(2021, 5, 19, 14, 18, 39, 124, DateTimeKind.Local).AddTicks(2114),
                            CreatedBy = "DataSeed",
                            Name = "Landscapes/Nature"
                        },
                        new
                        {
                            Id = 9,
                            Created = new DateTime(2021, 5, 19, 14, 18, 39, 124, DateTimeKind.Local).AddTicks(2117),
                            CreatedBy = "DataSeed",
                            Name = "Heraldry/Coat of Arms"
                        },
                        new
                        {
                            Id = 10,
                            Created = new DateTime(2021, 5, 19, 14, 18, 39, 124, DateTimeKind.Local).AddTicks(2120),
                            CreatedBy = "DataSeed",
                            Name = "Water and Sanitation"
                        },
                        new
                        {
                            Id = 11,
                            Created = new DateTime(2021, 5, 19, 14, 18, 39, 124, DateTimeKind.Local).AddTicks(2162),
                            CreatedBy = "DataSeed",
                            Name = "Agriculture/Farming"
                        },
                        new
                        {
                            Id = 12,
                            Created = new DateTime(2021, 5, 19, 14, 18, 39, 124, DateTimeKind.Local).AddTicks(2164),
                            CreatedBy = "DataSeed",
                            Name = "Golf"
                        },
                        new
                        {
                            Id = 13,
                            Created = new DateTime(2021, 5, 19, 14, 18, 39, 124, DateTimeKind.Local).AddTicks(2167),
                            CreatedBy = "DataSeed",
                            Name = "Cartoon"
                        },
                        new
                        {
                            Id = 14,
                            Created = new DateTime(2021, 5, 19, 14, 18, 39, 124, DateTimeKind.Local).AddTicks(2169),
                            CreatedBy = "DataSeed",
                            Name = "Lizards"
                        },
                        new
                        {
                            Id = 15,
                            Created = new DateTime(2021, 5, 19, 14, 18, 39, 124, DateTimeKind.Local).AddTicks(2171),
                            CreatedBy = "DataSeed",
                            Name = "Law"
                        },
                        new
                        {
                            Id = 16,
                            Created = new DateTime(2021, 5, 19, 14, 18, 39, 124, DateTimeKind.Local).AddTicks(2174),
                            CreatedBy = "DataSeed",
                            Name = "Swimming"
                        },
                        new
                        {
                            Id = 17,
                            Created = new DateTime(2021, 5, 19, 14, 18, 39, 124, DateTimeKind.Local).AddTicks(2176),
                            CreatedBy = "DataSeed",
                            Name = "Stamp on Stamps"
                        },
                        new
                        {
                            Id = 18,
                            Created = new DateTime(2021, 5, 19, 14, 18, 39, 124, DateTimeKind.Local).AddTicks(2179),
                            CreatedBy = "DataSeed",
                            Name = "Frogs"
                        },
                        new
                        {
                            Id = 19,
                            Created = new DateTime(2021, 5, 19, 14, 18, 39, 124, DateTimeKind.Local).AddTicks(2182),
                            CreatedBy = "DataSeed",
                            Name = "Costumes"
                        },
                        new
                        {
                            Id = 20,
                            Created = new DateTime(2021, 5, 19, 14, 18, 39, 124, DateTimeKind.Local).AddTicks(2184),
                            CreatedBy = "DataSeed",
                            Name = "Child Paintings"
                        },
                        new
                        {
                            Id = 21,
                            Created = new DateTime(2021, 5, 19, 14, 18, 39, 124, DateTimeKind.Local).AddTicks(2186),
                            CreatedBy = "DataSeed",
                            Name = "Turtles"
                        },
                        new
                        {
                            Id = 22,
                            Created = new DateTime(2021, 5, 19, 14, 18, 39, 124, DateTimeKind.Local).AddTicks(2189),
                            CreatedBy = "DataSeed",
                            Name = "WWF"
                        },
                        new
                        {
                            Id = 23,
                            Created = new DateTime(2021, 5, 19, 14, 18, 39, 124, DateTimeKind.Local).AddTicks(2191),
                            CreatedBy = "DataSeed",
                            Name = "Religion/Churches"
                        },
                        new
                        {
                            Id = 24,
                            Created = new DateTime(2021, 5, 19, 14, 18, 39, 124, DateTimeKind.Local).AddTicks(2194),
                            CreatedBy = "DataSeed",
                            Name = "Lions International"
                        },
                        new
                        {
                            Id = 25,
                            Created = new DateTime(2021, 5, 19, 14, 18, 39, 124, DateTimeKind.Local).AddTicks(2196),
                            CreatedBy = "DataSeed",
                            Name = "Boer War"
                        },
                        new
                        {
                            Id = 26,
                            Created = new DateTime(2021, 5, 19, 14, 18, 39, 124, DateTimeKind.Local).AddTicks(2198),
                            CreatedBy = "DataSeed",
                            Name = "Red Cross"
                        },
                        new
                        {
                            Id = 27,
                            Created = new DateTime(2021, 5, 19, 14, 18, 39, 124, DateTimeKind.Local).AddTicks(2201),
                            CreatedBy = "DataSeed",
                            Name = "Trees"
                        },
                        new
                        {
                            Id = 28,
                            Created = new DateTime(2021, 5, 19, 14, 18, 39, 124, DateTimeKind.Local).AddTicks(2203),
                            CreatedBy = "DataSeed",
                            Name = "Easter"
                        },
                        new
                        {
                            Id = 29,
                            Created = new DateTime(2021, 5, 19, 14, 18, 39, 124, DateTimeKind.Local).AddTicks(2205),
                            CreatedBy = "DataSeed",
                            Name = "Dogs"
                        },
                        new
                        {
                            Id = 30,
                            Created = new DateTime(2021, 5, 19, 14, 18, 39, 124, DateTimeKind.Local).AddTicks(2207),
                            CreatedBy = "DataSeed",
                            Name = "Transport"
                        },
                        new
                        {
                            Id = 31,
                            Created = new DateTime(2021, 5, 19, 14, 18, 39, 124, DateTimeKind.Local).AddTicks(2210),
                            CreatedBy = "DataSeed",
                            Name = "Gem Stones/Jewels"
                        },
                        new
                        {
                            Id = 32,
                            Created = new DateTime(2021, 5, 19, 14, 18, 39, 124, DateTimeKind.Local).AddTicks(2212),
                            CreatedBy = "DataSeed",
                            Name = "Railway/Trains"
                        },
                        new
                        {
                            Id = 33,
                            Created = new DateTime(2021, 5, 19, 14, 18, 39, 124, DateTimeKind.Local).AddTicks(2214),
                            CreatedBy = "DataSeed",
                            Name = "History"
                        },
                        new
                        {
                            Id = 34,
                            Created = new DateTime(2021, 5, 19, 14, 18, 39, 124, DateTimeKind.Local).AddTicks(2218),
                            CreatedBy = "DataSeed",
                            Name = "Shells"
                        },
                        new
                        {
                            Id = 35,
                            Created = new DateTime(2021, 5, 19, 14, 18, 39, 124, DateTimeKind.Local).AddTicks(2220),
                            CreatedBy = "DataSeed",
                            Name = "Geology"
                        },
                        new
                        {
                            Id = 36,
                            Created = new DateTime(2021, 5, 19, 14, 18, 39, 124, DateTimeKind.Local).AddTicks(2223),
                            CreatedBy = "DataSeed",
                            Name = "Cats"
                        },
                        new
                        {
                            Id = 37,
                            Created = new DateTime(2021, 5, 19, 14, 18, 39, 124, DateTimeKind.Local).AddTicks(2225),
                            CreatedBy = "DataSeed",
                            Name = "Grasses"
                        },
                        new
                        {
                            Id = 38,
                            Created = new DateTime(2021, 5, 19, 14, 18, 39, 124, DateTimeKind.Local).AddTicks(2228),
                            CreatedBy = "DataSeed",
                            Name = "Whales"
                        },
                        new
                        {
                            Id = 39,
                            Created = new DateTime(2021, 5, 19, 14, 18, 39, 124, DateTimeKind.Local).AddTicks(2230),
                            CreatedBy = "DataSeed",
                            Name = "Apartheid"
                        },
                        new
                        {
                            Id = 40,
                            Created = new DateTime(2021, 5, 19, 14, 18, 39, 124, DateTimeKind.Local).AddTicks(2232),
                            CreatedBy = "DataSeed",
                            Name = "Government and Politics"
                        },
                        new
                        {
                            Id = 41,
                            Created = new DateTime(2021, 5, 19, 14, 18, 39, 124, DateTimeKind.Local).AddTicks(2234),
                            CreatedBy = "DataSeed",
                            Name = "Football/Soccer"
                        },
                        new
                        {
                            Id = 42,
                            Created = new DateTime(2021, 5, 19, 14, 18, 39, 124, DateTimeKind.Local).AddTicks(2237),
                            CreatedBy = "DataSeed",
                            Name = "Tennis"
                        },
                        new
                        {
                            Id = 43,
                            Created = new DateTime(2021, 5, 19, 14, 18, 39, 124, DateTimeKind.Local).AddTicks(2239),
                            CreatedBy = "DataSeed",
                            Name = "Hockey"
                        },
                        new
                        {
                            Id = 44,
                            Created = new DateTime(2021, 5, 19, 14, 18, 39, 124, DateTimeKind.Local).AddTicks(2241),
                            CreatedBy = "DataSeed",
                            Name = "Chicken"
                        },
                        new
                        {
                            Id = 45,
                            Created = new DateTime(2021, 5, 19, 14, 18, 39, 124, DateTimeKind.Local).AddTicks(2244),
                            CreatedBy = "DataSeed",
                            Name = "Nursing"
                        },
                        new
                        {
                            Id = 46,
                            Created = new DateTime(2021, 5, 19, 14, 18, 39, 124, DateTimeKind.Local).AddTicks(2246),
                            CreatedBy = "DataSeed",
                            Name = "Flags"
                        },
                        new
                        {
                            Id = 47,
                            Created = new DateTime(2021, 5, 19, 14, 18, 39, 124, DateTimeKind.Local).AddTicks(2248),
                            CreatedBy = "DataSeed",
                            Name = "Equestrian"
                        },
                        new
                        {
                            Id = 48,
                            Created = new DateTime(2021, 5, 19, 14, 18, 39, 124, DateTimeKind.Local).AddTicks(2251),
                            CreatedBy = "DataSeed",
                            Name = "Disabled"
                        },
                        new
                        {
                            Id = 49,
                            Created = new DateTime(2021, 5, 19, 14, 18, 39, 124, DateTimeKind.Local).AddTicks(2253),
                            CreatedBy = "DataSeed",
                            Name = "Owls"
                        },
                        new
                        {
                            Id = 50,
                            Created = new DateTime(2021, 5, 19, 14, 18, 39, 124, DateTimeKind.Local).AddTicks(2255),
                            CreatedBy = "DataSeed",
                            Name = "Definitive Series"
                        },
                        new
                        {
                            Id = 51,
                            Created = new DateTime(2021, 5, 19, 14, 18, 39, 124, DateTimeKind.Local).AddTicks(2257),
                            CreatedBy = "DataSeed",
                            Name = "Girl Guides"
                        },
                        new
                        {
                            Id = 52,
                            Created = new DateTime(2021, 5, 19, 14, 18, 39, 124, DateTimeKind.Local).AddTicks(2260),
                            CreatedBy = "DataSeed",
                            Name = "Maps"
                        },
                        new
                        {
                            Id = 53,
                            Created = new DateTime(2021, 5, 19, 14, 18, 39, 124, DateTimeKind.Local).AddTicks(2262),
                            CreatedBy = "DataSeed",
                            Name = "Christmas"
                        },
                        new
                        {
                            Id = 54,
                            Created = new DateTime(2021, 5, 19, 14, 18, 39, 124, DateTimeKind.Local).AddTicks(2264),
                            CreatedBy = "DataSeed",
                            Name = "Science and Technology"
                        },
                        new
                        {
                            Id = 55,
                            Created = new DateTime(2021, 5, 19, 14, 18, 39, 124, DateTimeKind.Local).AddTicks(2267),
                            CreatedBy = "DataSeed",
                            Name = "Hares/Rabbits"
                        },
                        new
                        {
                            Id = 56,
                            Created = new DateTime(2021, 5, 19, 14, 18, 39, 124, DateTimeKind.Local).AddTicks(2269),
                            CreatedBy = "DataSeed",
                            Name = "Horses"
                        },
                        new
                        {
                            Id = 57,
                            Created = new DateTime(2021, 5, 19, 14, 18, 39, 124, DateTimeKind.Local).AddTicks(2272),
                            CreatedBy = "DataSeed",
                            Name = "Wines and Beer"
                        },
                        new
                        {
                            Id = 58,
                            Created = new DateTime(2021, 5, 19, 14, 18, 39, 124, DateTimeKind.Local).AddTicks(2274),
                            CreatedBy = "DataSeed",
                            Name = "Helicopters"
                        },
                        new
                        {
                            Id = 59,
                            Created = new DateTime(2021, 5, 19, 14, 18, 39, 124, DateTimeKind.Local).AddTicks(2276),
                            CreatedBy = "DataSeed",
                            Name = "Submarines"
                        },
                        new
                        {
                            Id = 60,
                            Created = new DateTime(2021, 5, 19, 14, 18, 39, 124, DateTimeKind.Local).AddTicks(2278),
                            CreatedBy = "DataSeed",
                            Name = "Monkeys and Baboons"
                        },
                        new
                        {
                            Id = 61,
                            Created = new DateTime(2021, 5, 19, 14, 18, 39, 124, DateTimeKind.Local).AddTicks(2281),
                            CreatedBy = "DataSeed",
                            Name = "Stamp Exhibition"
                        },
                        new
                        {
                            Id = 62,
                            Created = new DateTime(2021, 5, 19, 14, 18, 39, 124, DateTimeKind.Local).AddTicks(2283),
                            CreatedBy = "DataSeed",
                            Name = "Fruits"
                        },
                        new
                        {
                            Id = 63,
                            Created = new DateTime(2021, 5, 19, 14, 18, 39, 124, DateTimeKind.Local).AddTicks(2285),
                            CreatedBy = "DataSeed",
                            Name = "Road Safety"
                        },
                        new
                        {
                            Id = 64,
                            Created = new DateTime(2021, 5, 19, 14, 18, 39, 124, DateTimeKind.Local).AddTicks(2288),
                            CreatedBy = "DataSeed",
                            Name = "Mountains"
                        },
                        new
                        {
                            Id = 65,
                            Created = new DateTime(2021, 5, 19, 14, 18, 39, 124, DateTimeKind.Local).AddTicks(2290),
                            CreatedBy = "DataSeed",
                            Name = "Forestry/Trees"
                        },
                        new
                        {
                            Id = 66,
                            Created = new DateTime(2021, 5, 19, 14, 18, 39, 124, DateTimeKind.Local).AddTicks(2293),
                            CreatedBy = "DataSeed",
                            Name = "Atletics"
                        },
                        new
                        {
                            Id = 67,
                            Created = new DateTime(2021, 5, 19, 14, 18, 39, 124, DateTimeKind.Local).AddTicks(2295),
                            CreatedBy = "DataSeed",
                            Name = "Voortrekkers"
                        },
                        new
                        {
                            Id = 68,
                            Created = new DateTime(2021, 5, 19, 14, 18, 39, 124, DateTimeKind.Local).AddTicks(2296),
                            CreatedBy = "DataSeed",
                            Name = "Insects"
                        },
                        new
                        {
                            Id = 69,
                            Created = new DateTime(2021, 5, 19, 14, 18, 39, 124, DateTimeKind.Local).AddTicks(2298),
                            CreatedBy = "DataSeed",
                            Name = "Roses"
                        },
                        new
                        {
                            Id = 70,
                            Created = new DateTime(2021, 5, 19, 14, 18, 39, 124, DateTimeKind.Local).AddTicks(2300),
                            CreatedBy = "DataSeed",
                            Name = "Tourism"
                        },
                        new
                        {
                            Id = 71,
                            Created = new DateTime(2021, 5, 19, 14, 18, 39, 124, DateTimeKind.Local).AddTicks(2302),
                            CreatedBy = "DataSeed",
                            Name = "Postal History"
                        },
                        new
                        {
                            Id = 72,
                            Created = new DateTime(2021, 5, 19, 14, 18, 39, 124, DateTimeKind.Local).AddTicks(2304),
                            CreatedBy = "DataSeed",
                            Name = "Musical Instruments"
                        },
                        new
                        {
                            Id = 73,
                            Created = new DateTime(2021, 5, 19, 14, 18, 39, 124, DateTimeKind.Local).AddTicks(2305),
                            CreatedBy = "DataSeed",
                            Name = "Music"
                        },
                        new
                        {
                            Id = 74,
                            Created = new DateTime(2021, 5, 19, 14, 18, 39, 124, DateTimeKind.Local).AddTicks(2308),
                            CreatedBy = "DataSeed",
                            Name = "Motorsport"
                        },
                        new
                        {
                            Id = 75,
                            Created = new DateTime(2021, 5, 19, 14, 18, 39, 124, DateTimeKind.Local).AddTicks(2309),
                            CreatedBy = "DataSeed",
                            Name = "Antarctica"
                        },
                        new
                        {
                            Id = 76,
                            Created = new DateTime(2021, 5, 19, 14, 18, 39, 124, DateTimeKind.Local).AddTicks(2312),
                            CreatedBy = "DataSeed",
                            Name = "Cricket"
                        },
                        new
                        {
                            Id = 77,
                            Created = new DateTime(2021, 5, 19, 14, 18, 39, 124, DateTimeKind.Local).AddTicks(2313),
                            CreatedBy = "DataSeed",
                            Name = "Health/Medicine"
                        },
                        new
                        {
                            Id = 78,
                            Created = new DateTime(2021, 5, 19, 14, 18, 39, 124, DateTimeKind.Local).AddTicks(2315),
                            CreatedBy = "DataSeed",
                            Name = "Platinum"
                        },
                        new
                        {
                            Id = 79,
                            Created = new DateTime(2021, 5, 19, 14, 18, 39, 124, DateTimeKind.Local).AddTicks(2318),
                            CreatedBy = "DataSeed",
                            Name = "Literature/Writers"
                        },
                        new
                        {
                            Id = 80,
                            Created = new DateTime(2021, 5, 19, 14, 18, 39, 124, DateTimeKind.Local).AddTicks(2319),
                            CreatedBy = "DataSeed",
                            Name = "Unicef"
                        },
                        new
                        {
                            Id = 81,
                            Created = new DateTime(2021, 5, 19, 14, 18, 39, 124, DateTimeKind.Local).AddTicks(2322),
                            CreatedBy = "DataSeed",
                            Name = "Rivers"
                        },
                        new
                        {
                            Id = 82,
                            Created = new DateTime(2021, 5, 19, 14, 18, 39, 124, DateTimeKind.Local).AddTicks(2323),
                            CreatedBy = "DataSeed",
                            Name = "Royals"
                        },
                        new
                        {
                            Id = 83,
                            Created = new DateTime(2021, 5, 19, 14, 18, 39, 124, DateTimeKind.Local).AddTicks(2326),
                            CreatedBy = "DataSeed",
                            Name = "National Festivals"
                        },
                        new
                        {
                            Id = 84,
                            Created = new DateTime(2021, 5, 19, 14, 18, 39, 124, DateTimeKind.Local).AddTicks(2328),
                            CreatedBy = "DataSeed",
                            Name = "United Nations"
                        },
                        new
                        {
                            Id = 85,
                            Created = new DateTime(2021, 5, 19, 14, 18, 39, 124, DateTimeKind.Local).AddTicks(2330),
                            CreatedBy = "DataSeed",
                            Name = "Manufacturing/Industries"
                        },
                        new
                        {
                            Id = 86,
                            Created = new DateTime(2021, 5, 19, 14, 18, 39, 124, DateTimeKind.Local).AddTicks(2332),
                            CreatedBy = "DataSeed",
                            Name = "Space"
                        },
                        new
                        {
                            Id = 87,
                            Created = new DateTime(2021, 5, 19, 14, 18, 39, 124, DateTimeKind.Local).AddTicks(2334),
                            CreatedBy = "DataSeed",
                            Name = "Fossils"
                        },
                        new
                        {
                            Id = 88,
                            Created = new DateTime(2021, 5, 19, 14, 18, 39, 124, DateTimeKind.Local).AddTicks(2336),
                            CreatedBy = "DataSeed",
                            Name = "Birds"
                        },
                        new
                        {
                            Id = 89,
                            Created = new DateTime(2021, 5, 19, 14, 18, 39, 124, DateTimeKind.Local).AddTicks(2338),
                            CreatedBy = "DataSeed",
                            Name = "Meteorology/Weather"
                        },
                        new
                        {
                            Id = 90,
                            Created = new DateTime(2021, 5, 19, 14, 18, 39, 124, DateTimeKind.Local).AddTicks(2363),
                            CreatedBy = "DataSeed",
                            Name = "Olympic Games"
                        },
                        new
                        {
                            Id = 91,
                            Created = new DateTime(2021, 5, 19, 14, 18, 39, 124, DateTimeKind.Local).AddTicks(2366),
                            CreatedBy = "DataSeed",
                            Name = "Astronomy"
                        },
                        new
                        {
                            Id = 92,
                            Created = new DateTime(2021, 5, 19, 14, 18, 39, 124, DateTimeKind.Local).AddTicks(2367),
                            CreatedBy = "DataSeed",
                            Name = "Weapons"
                        },
                        new
                        {
                            Id = 93,
                            Created = new DateTime(2021, 5, 19, 14, 18, 39, 124, DateTimeKind.Local).AddTicks(2370),
                            CreatedBy = "DataSeed",
                            Name = "Millenium"
                        },
                        new
                        {
                            Id = 94,
                            Created = new DateTime(2021, 5, 19, 14, 18, 39, 124, DateTimeKind.Local).AddTicks(2371),
                            CreatedBy = "DataSeed",
                            Name = "Spiders"
                        },
                        new
                        {
                            Id = 95,
                            Created = new DateTime(2021, 5, 19, 14, 18, 39, 124, DateTimeKind.Local).AddTicks(2374),
                            CreatedBy = "DataSeed",
                            Name = "Settlers"
                        },
                        new
                        {
                            Id = 96,
                            Created = new DateTime(2021, 5, 19, 14, 18, 39, 124, DateTimeKind.Local).AddTicks(2375),
                            CreatedBy = "DataSeed",
                            Name = "Boxing"
                        },
                        new
                        {
                            Id = 97,
                            Created = new DateTime(2021, 5, 19, 14, 18, 39, 124, DateTimeKind.Local).AddTicks(2377),
                            CreatedBy = "DataSeed",
                            Name = "Windmills"
                        },
                        new
                        {
                            Id = 98,
                            Created = new DateTime(2021, 5, 19, 14, 18, 39, 124, DateTimeKind.Local).AddTicks(2379),
                            CreatedBy = "DataSeed",
                            Name = "Mining/Minerals"
                        },
                        new
                        {
                            Id = 99,
                            Created = new DateTime(2021, 5, 19, 14, 18, 39, 124, DateTimeKind.Local).AddTicks(2381),
                            CreatedBy = "DataSeed",
                            Name = "Forts and Castles"
                        },
                        new
                        {
                            Id = 100,
                            Created = new DateTime(2021, 5, 19, 14, 18, 39, 124, DateTimeKind.Local).AddTicks(2383),
                            CreatedBy = "DataSeed",
                            Name = "Diplomacy"
                        },
                        new
                        {
                            Id = 101,
                            Created = new DateTime(2021, 5, 19, 14, 18, 39, 124, DateTimeKind.Local).AddTicks(2385),
                            CreatedBy = "DataSeed",
                            Name = "Mushrooms/Fungi"
                        },
                        new
                        {
                            Id = 102,
                            Created = new DateTime(2021, 5, 19, 14, 18, 39, 124, DateTimeKind.Local).AddTicks(2387),
                            CreatedBy = "DataSeed",
                            Name = "Dams"
                        },
                        new
                        {
                            Id = 103,
                            Created = new DateTime(2021, 5, 19, 14, 18, 39, 124, DateTimeKind.Local).AddTicks(2389),
                            CreatedBy = "DataSeed",
                            Name = "Languages"
                        },
                        new
                        {
                            Id = 104,
                            Created = new DateTime(2021, 5, 19, 14, 18, 39, 124, DateTimeKind.Local).AddTicks(2391),
                            CreatedBy = "DataSeed",
                            Name = "Sharks"
                        },
                        new
                        {
                            Id = 105,
                            Created = new DateTime(2021, 5, 19, 14, 18, 39, 124, DateTimeKind.Local).AddTicks(2394),
                            CreatedBy = "DataSeed",
                            Name = "Arts/Culture/Traditions"
                        },
                        new
                        {
                            Id = 106,
                            Created = new DateTime(2021, 5, 19, 14, 18, 39, 124, DateTimeKind.Local).AddTicks(2396),
                            CreatedBy = "DataSeed",
                            Name = "Archaeology"
                        },
                        new
                        {
                            Id = 107,
                            Created = new DateTime(2021, 5, 19, 14, 18, 39, 124, DateTimeKind.Local).AddTicks(2398),
                            CreatedBy = "DataSeed",
                            Name = "Telecommunication"
                        },
                        new
                        {
                            Id = 108,
                            Created = new DateTime(2021, 5, 19, 14, 18, 39, 124, DateTimeKind.Local).AddTicks(2400),
                            CreatedBy = "DataSeed",
                            Name = "Rugby"
                        },
                        new
                        {
                            Id = 109,
                            Created = new DateTime(2021, 5, 19, 14, 18, 39, 124, DateTimeKind.Local).AddTicks(2402),
                            CreatedBy = "DataSeed",
                            Name = "Fish and Marine Life"
                        },
                        new
                        {
                            Id = 110,
                            Created = new DateTime(2021, 5, 19, 14, 18, 39, 124, DateTimeKind.Local).AddTicks(2403),
                            CreatedBy = "DataSeed",
                            Name = "van Riebeeck"
                        },
                        new
                        {
                            Id = 111,
                            Created = new DateTime(2021, 5, 19, 14, 18, 39, 124, DateTimeKind.Local).AddTicks(2406),
                            CreatedBy = "DataSeed",
                            Name = "Orchids"
                        },
                        new
                        {
                            Id = 112,
                            Created = new DateTime(2021, 5, 19, 14, 18, 39, 124, DateTimeKind.Local).AddTicks(2407),
                            CreatedBy = "DataSeed",
                            Name = "Jan van Riebeeck"
                        },
                        new
                        {
                            Id = 113,
                            Created = new DateTime(2021, 5, 19, 14, 18, 39, 124, DateTimeKind.Local).AddTicks(2410),
                            CreatedBy = "DataSeed",
                            Name = "Flight and Aircraft"
                        },
                        new
                        {
                            Id = 114,
                            Created = new DateTime(2021, 5, 19, 14, 18, 39, 124, DateTimeKind.Local).AddTicks(2411),
                            CreatedBy = "DataSeed",
                            Name = "Telephone"
                        },
                        new
                        {
                            Id = 115,
                            Created = new DateTime(2021, 5, 19, 14, 18, 39, 124, DateTimeKind.Local).AddTicks(2413),
                            CreatedBy = "DataSeed",
                            Name = "Folklore"
                        },
                        new
                        {
                            Id = 116,
                            Created = new DateTime(2021, 5, 19, 14, 18, 39, 124, DateTimeKind.Local).AddTicks(2415),
                            CreatedBy = "DataSeed",
                            Name = "Cars"
                        },
                        new
                        {
                            Id = 117,
                            Created = new DateTime(2021, 5, 19, 14, 18, 39, 124, DateTimeKind.Local).AddTicks(2417),
                            CreatedBy = "DataSeed",
                            Name = "Gold"
                        },
                        new
                        {
                            Id = 118,
                            Created = new DateTime(2021, 5, 19, 14, 18, 39, 124, DateTimeKind.Local).AddTicks(2418),
                            CreatedBy = "DataSeed",
                            Name = "Afrikaans language"
                        },
                        new
                        {
                            Id = 119,
                            Created = new DateTime(2021, 5, 19, 14, 18, 39, 124, DateTimeKind.Local).AddTicks(2420),
                            CreatedBy = "DataSeed",
                            Name = "Communication"
                        },
                        new
                        {
                            Id = 120,
                            Created = new DateTime(2021, 5, 19, 14, 18, 39, 124, DateTimeKind.Local).AddTicks(2421),
                            CreatedBy = "DataSeed",
                            Name = "Boy Scouts"
                        },
                        new
                        {
                            Id = 121,
                            Created = new DateTime(2021, 5, 19, 14, 18, 39, 124, DateTimeKind.Local).AddTicks(2423),
                            CreatedBy = "DataSeed",
                            Name = "Bats"
                        },
                        new
                        {
                            Id = 122,
                            Created = new DateTime(2021, 5, 19, 14, 18, 39, 124, DateTimeKind.Local).AddTicks(2424),
                            CreatedBy = "DataSeed",
                            Name = "Solar System"
                        },
                        new
                        {
                            Id = 123,
                            Created = new DateTime(2021, 5, 19, 14, 18, 39, 124, DateTimeKind.Local).AddTicks(2426),
                            CreatedBy = "DataSeed",
                            Name = "Architecture"
                        },
                        new
                        {
                            Id = 124,
                            Created = new DateTime(2021, 5, 19, 14, 18, 39, 124, DateTimeKind.Local).AddTicks(2427),
                            CreatedBy = "DataSeed",
                            Name = "Scuptures"
                        },
                        new
                        {
                            Id = 125,
                            Created = new DateTime(2021, 5, 19, 14, 18, 39, 124, DateTimeKind.Local).AddTicks(2429),
                            CreatedBy = "DataSeed",
                            Name = "Dinosaurs"
                        },
                        new
                        {
                            Id = 126,
                            Created = new DateTime(2021, 5, 19, 14, 18, 39, 124, DateTimeKind.Local).AddTicks(2431),
                            CreatedBy = "DataSeed",
                            Name = "Presidents and Leaders"
                        },
                        new
                        {
                            Id = 127,
                            Created = new DateTime(2021, 5, 19, 14, 18, 39, 124, DateTimeKind.Local).AddTicks(2432),
                            CreatedBy = "DataSeed",
                            Name = "Bridges"
                        },
                        new
                        {
                            Id = 128,
                            Created = new DateTime(2021, 5, 19, 14, 18, 39, 124, DateTimeKind.Local).AddTicks(2434),
                            CreatedBy = "DataSeed",
                            Name = "Museums"
                        },
                        new
                        {
                            Id = 129,
                            Created = new DateTime(2021, 5, 19, 14, 18, 39, 124, DateTimeKind.Local).AddTicks(2435),
                            CreatedBy = "DataSeed",
                            Name = "Hunting"
                        },
                        new
                        {
                            Id = 130,
                            Created = new DateTime(2021, 5, 19, 14, 18, 39, 124, DateTimeKind.Local).AddTicks(2438),
                            CreatedBy = "DataSeed",
                            Name = "Flora/Flowers"
                        },
                        new
                        {
                            Id = 131,
                            Created = new DateTime(2021, 5, 19, 14, 18, 39, 124, DateTimeKind.Local).AddTicks(2440),
                            CreatedBy = "DataSeed",
                            Name = "Constitution"
                        },
                        new
                        {
                            Id = 132,
                            Created = new DateTime(2021, 5, 19, 14, 18, 39, 124, DateTimeKind.Local).AddTicks(2441),
                            CreatedBy = "DataSeed",
                            Name = "Balloon Flights"
                        },
                        new
                        {
                            Id = 133,
                            Created = new DateTime(2021, 5, 19, 14, 18, 39, 124, DateTimeKind.Local).AddTicks(2443),
                            CreatedBy = "DataSeed",
                            Name = "Snails"
                        },
                        new
                        {
                            Id = 134,
                            Created = new DateTime(2021, 5, 19, 14, 18, 39, 124, DateTimeKind.Local).AddTicks(2444),
                            CreatedBy = "DataSeed",
                            Name = "Towns/Cities History"
                        },
                        new
                        {
                            Id = 135,
                            Created = new DateTime(2021, 5, 19, 14, 18, 39, 124, DateTimeKind.Local).AddTicks(2446),
                            CreatedBy = "DataSeed",
                            Name = "Butterflies"
                        },
                        new
                        {
                            Id = 136,
                            Created = new DateTime(2021, 5, 19, 14, 18, 39, 124, DateTimeKind.Local).AddTicks(2447),
                            CreatedBy = "DataSeed",
                            Name = "Monuments"
                        },
                        new
                        {
                            Id = 137,
                            Created = new DateTime(2021, 5, 19, 14, 18, 39, 124, DateTimeKind.Local).AddTicks(2449),
                            CreatedBy = "DataSeed",
                            Name = "Wildlife"
                        },
                        new
                        {
                            Id = 138,
                            Created = new DateTime(2021, 5, 19, 14, 18, 39, 124, DateTimeKind.Local).AddTicks(2450),
                            CreatedBy = "DataSeed",
                            Name = "Community Services"
                        },
                        new
                        {
                            Id = 139,
                            Created = new DateTime(2021, 5, 19, 14, 18, 39, 124, DateTimeKind.Local).AddTicks(2452),
                            CreatedBy = "DataSeed",
                            Name = "Uniforms"
                        },
                        new
                        {
                            Id = 140,
                            Created = new DateTime(2021, 5, 19, 14, 18, 39, 124, DateTimeKind.Local).AddTicks(2454),
                            CreatedBy = "DataSeed",
                            Name = "Ships/Maritime"
                        },
                        new
                        {
                            Id = 141,
                            Created = new DateTime(2021, 5, 19, 14, 18, 39, 124, DateTimeKind.Local).AddTicks(2455),
                            CreatedBy = "DataSeed",
                            Name = "Reptiles"
                        },
                        new
                        {
                            Id = 142,
                            Created = new DateTime(2021, 5, 19, 14, 18, 39, 124, DateTimeKind.Local).AddTicks(2457),
                            CreatedBy = "DataSeed",
                            Name = "Triangle Stamps"
                        },
                        new
                        {
                            Id = 143,
                            Created = new DateTime(2021, 5, 19, 14, 18, 39, 124, DateTimeKind.Local).AddTicks(2458),
                            CreatedBy = "DataSeed",
                            Name = "Energy"
                        },
                        new
                        {
                            Id = 144,
                            Created = new DateTime(2021, 5, 19, 14, 18, 39, 124, DateTimeKind.Local).AddTicks(2460),
                            CreatedBy = "DataSeed",
                            Name = "Child"
                        },
                        new
                        {
                            Id = 145,
                            Created = new DateTime(2021, 5, 19, 14, 18, 39, 124, DateTimeKind.Local).AddTicks(2461),
                            CreatedBy = "DataSeed",
                            Name = "Snakes"
                        },
                        new
                        {
                            Id = 146,
                            Created = new DateTime(2021, 5, 19, 14, 18, 39, 124, DateTimeKind.Local).AddTicks(2463),
                            CreatedBy = "DataSeed",
                            Name = "Stamp Day"
                        },
                        new
                        {
                            Id = 147,
                            Created = new DateTime(2021, 5, 19, 14, 18, 39, 124, DateTimeKind.Local).AddTicks(2464),
                            CreatedBy = "DataSeed",
                            Name = "Watersports"
                        },
                        new
                        {
                            Id = 148,
                            Created = new DateTime(2021, 5, 19, 14, 18, 39, 124, DateTimeKind.Local).AddTicks(2466),
                            CreatedBy = "DataSeed",
                            Name = "Waterfalls"
                        },
                        new
                        {
                            Id = 149,
                            Created = new DateTime(2021, 5, 19, 14, 18, 39, 124, DateTimeKind.Local).AddTicks(2468),
                            CreatedBy = "DataSeed",
                            Name = "Military"
                        },
                        new
                        {
                            Id = 150,
                            Created = new DateTime(2021, 5, 19, 14, 18, 39, 124, DateTimeKind.Local).AddTicks(2469),
                            CreatedBy = "DataSeed",
                            Name = "Rotary International"
                        },
                        new
                        {
                            Id = 151,
                            Created = new DateTime(2021, 5, 19, 14, 18, 39, 124, DateTimeKind.Local).AddTicks(2471),
                            CreatedBy = "DataSeed",
                            Name = "Paintings"
                        },
                        new
                        {
                            Id = 152,
                            Created = new DateTime(2021, 5, 19, 14, 18, 39, 124, DateTimeKind.Local).AddTicks(2472),
                            CreatedBy = "DataSeed",
                            Name = "Education"
                        });
                });

            modelBuilder.Entity("Philcosa.Domain.Entities.Postcard", b =>
                {
                    b.HasOne("Philcosa.Domain.Entities.Country", "Country")
                        .WithOne("Postcard")
                        .HasForeignKey("Philcosa.Domain.Entities.Postcard", "CountryId");

                    b.HasOne("Philcosa.Domain.Entities.IssuedByEntity", "IssuedBy")
                        .WithOne("Postcard")
                        .HasForeignKey("Philcosa.Domain.Entities.Postcard", "IssuedById");

                    b.HasOne("Philcosa.Domain.Entities.PostcardType", "PostcardType")
                        .WithOne("Postcard")
                        .HasForeignKey("Philcosa.Domain.Entities.Postcard", "PostcardTypeId");

                    b.HasOne("Philcosa.Domain.Entities.PostcardValue", "Value")
                        .WithOne("Postcard")
                        .HasForeignKey("Philcosa.Domain.Entities.Postcard", "PostcardValueId");

                    b.Navigation("Country");

                    b.Navigation("IssuedBy");

                    b.Navigation("PostcardType");

                    b.Navigation("Value");
                });

            modelBuilder.Entity("Philcosa.Domain.Entities.PostcardTheme", b =>
                {
                    b.HasOne("Philcosa.Domain.Entities.Postcard", "Postcard")
                        .WithMany("PostcardThemes")
                        .HasForeignKey("PostcardId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Philcosa.Domain.Entities.Theme", "Theme")
                        .WithMany("PostcardThemes")
                        .HasForeignKey("ThemeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Postcard");

                    b.Navigation("Theme");
                });

            modelBuilder.Entity("Philcosa.Domain.Entities.Country", b =>
                {
                    b.Navigation("Postcard");
                });

            modelBuilder.Entity("Philcosa.Domain.Entities.IssuedByEntity", b =>
                {
                    b.Navigation("Postcard");
                });

            modelBuilder.Entity("Philcosa.Domain.Entities.Postcard", b =>
                {
                    b.Navigation("PostcardThemes");
                });

            modelBuilder.Entity("Philcosa.Domain.Entities.PostcardType", b =>
                {
                    b.Navigation("Postcard");
                });

            modelBuilder.Entity("Philcosa.Domain.Entities.PostcardValue", b =>
                {
                    b.Navigation("Postcard");
                });

            modelBuilder.Entity("Philcosa.Domain.Entities.Theme", b =>
                {
                    b.Navigation("PostcardThemes");
                });
#pragma warning restore 612, 618
        }
    }
}
